### ISSUE TITLE
[1.18.1] Unable to reconnect to server

### ISSUE THREAD

**Issue by itsdinkd** [Aurilisdev/Physica#114]
This mod prevents players from joining the server back if they leave or disconnect in same session.

**Reproduce;**
join server
leave server
join back
get disconnected

For some reason, its saying the server has incomplete tags... no idea why... but its coming from this mod (I tested one by one, and I was able to join after turning off the electrodynamic suite of mods and itself)

```java
"[22:52:18] [Render thread/WARN]: Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:block]=[forge:storage_blocks/steel, forge:storage_blocks/tin, forge:storage_blocks/aluminum, forge:storage_blocks/bronze, forge:storage_blocks/lead]}"```

That Warning is actually a disconnect and will not let you join.

**Comment by aurilisdev** [comment]
That is not enough for me to actually understand any of ur error. It makes no sense unless ur server is outdated or has a different version. This doesn't happen to me nor other people.

**Comment by itsdinkd** [comment]
No the server is not outdated. I'm using latest mods in my modpack, latest
forge loader. For some reason, when i have electrodynamics it gives issues
about the tags I posted above that your mod is trying to set in its own
datapack.

**Comment by itsdinkd** [comment]
Have you tested in a server environment and by reconnecting after join?

**Comment by itsdinkd** [comment]
Also maybe it's because these blocks do not actually exist? Usually that error I posted occurs when you are trying to tag a entity/block/item that doesn't exist.

**Comment by aurilisdev** [comment]
> Have you tested in a server environment and by reconnecting after join?

There is an official mudpack and server for all these mods so yes I am sure this works perfectly fine as I play on it my self.
Those blocks also do exist. If I get more info about this I MIGHT be able to fix it but from this info only I can't really confirm its an issue with electrodynamics. Will look into the resource blocks and see if I register them weirdly but this should not be the case. If you get more info then reopen this but otherwise I can't do more about this. If I encounter this issue myself in the future I will see if I can fix it but joining a server with the mods is not an issue :/

**Comment by itsdinkd** [comment]
was this fixed? the issue wasn't joining a server, it was rejoining a server.
