### ISSUE TITLE
Particle cannot be cast to livingbase

### ISSUE THREAD

**Issue by SoonBanned** [Aurilisdev/Physica#15]
Hello, I'm stuck with this error https://pastebin.com/kmf4yUfe, it happens everytime I login in my server and the recent change that I've made is to set a config in EnderIO from true to false because it was spamming the console (To be precise I change "Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]") So can you help me please because as far as I can read the crash report it's a particle of your mod that's crashing x)

**Comment by SoonBanned** [comment]
I'm using physica and the 2 addons in 1.0.0.3

**Comment by aurilisdev** [comment]
I am very sorry but I don't think that this is an issue with Physica itself. I have never gotten that error myself and if it is an issue with EnderIO which they have stated may cause issues with other mods then I am afraid you must talk with them instead of me. The issue doesn't actually do anything inside of Physica itself. It looks like another mod has made Minecraft itself try to turn an entityparticle into a living entity which is a mob. The particle itself is not a mob so this issue should never have occurred with Physica itself. Are you sure that the only thing you did was change that config. Did you not try to spawn the particle in a powered spawner or something like that?

**Comment by SoonBanned** [comment]
Sorry it was a huge mistake I forgot to say when I found the reason. It was just a fail because I forgot to make the clients got the change too, I made the config in server only and there was a conflict. Thanks for helping ^^

**Comment by aurilisdev** [comment]
No problem :)
