### ISSUE TITLE
Fission meltdown

### ISSUE THREAD

**Issue by Grieferson** [Aurilisdev/Physica#22]
So I got to experience a Physica fission reactor meltdown as a result of a server crash.  The melted reactor was a few blocks above bedrock, but it still managed to vaporize all water in the chunk, including all the seawater above it.

Becauase of the configuration of the containment around the reactor I had to fly to try and break the melted reactor, but I could not break the melted reactor in the time it took a brand new hazmat suit to decay and fail.   I had to get help from a mod to remove the melted reactor.

The reactor was properly configured with thermometer and control rod.  It melted down through no fault of my own, and it rendered the entire chunk unusable.  While I understand that reactor accidents should have serious consequences, I can say that I will never build or advise anyone to build a Physica fission reactor again due to the very high cost of reactor failure.  And fission reactor failure is highly probable when the server crashes.

So, please remove the melted reactor mechanic until you can figure out how to prevent the reactors from exploding during server crashes.  Also, it is not reasonable that a melted reactor vaporizes the entire ocean in the chunk.

Kind Regards - Grieferson

**Comment by aurilisdev** [comment]
I added a timer so that reactors do not meltdown during the first 2.5 seconds of it being loaded. The extreme danger of a melted reactor is on purpose so that it is actually very dangerous. I would advise you to use the insertable control rod instead of a thermometer as that is alot safer. I will add text saying that the normal control rod is only 99.999999% safe as this doesnt happen unless you are extremely unlucky with how the water evaporates. As for the seawater getting evaporated, i can not see how this could have happened if the reactor blew up at bedrock level. There is nowhere in the code where this can actually happen unless the universe decided to change som bits in your pc.
